name: simple_rest_service
description: A flutter package to help with Rest API integration.
version: 0.2.0 #dart pub publish
homepage: https://github.com/Juniorlpes/rest_service

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  ansicolor: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.4

# The following section is specific to Flutter packages.
flutter:
